sms <- read.csv("sms_spam.csv", stringsAsFactors= FALSE)
sms_facotortype<-factor(sms$type)
table(sms_facotortype)
#install.packages("tm")
library("tm")
corpus<-VCorpus(VectorSource(sms$text))
#head(corpus)
print(corpus)
inspect(corpus[1:2])
as.character(corpus[[1]])
lapply(corpus[1:2],as.character)
corpus_clean<-tm_map(corpus,content_transformer(tolower))
as.character(corpus[[1]])
as.character(corpus_clean[[1]])
corpus_clean<-tm_map(corpus_clean, removeNumbers)
corpus_clean<-tm_map(corpus_clean,removeWords,stopwords())
corpus_clean<-tm_map(corpus_clean,removePunctuation)
removePunctuation("hello...world")
library(SnowballC)
wordStem(c("learning","learned"))
corpus_clean<-tm_map(corpus_clean,stemDocument)
corpus_clean<-tm_map(corpus_clean,stripWhitespace)
as.character(corpus[[1]])
as.character(corpus_clean[[1]])
as.character(corpus_clean[1:4])
sms_dtm<- DocumentTermMatrix(corpus_clean)
sms_dtm_train<-sms_dtm[1:4169,]
sms_dtm_test<-sms_dtm[4170:5574,]
sms_train_labels<-sms[1:4169,]$type
sms_test_labels<-sms[4170:5574,]$type
head(sms_test_labels)
prop.table(table(sms_train_labels))
prop.table(table(sms_test_labels))
#install.packages("wordcloud")
library("wordcloud")
wordcloud(corpus_clean,min.freq = 50,random.order = FALSE)
spam<-subset(sms, type=='spam')
ham<-subset(sms, type=='ham')
wordcloud(spam$text, max.words = 40, scale = c(3,0.5))
wordcloud(ham$text, max.words = 40, scale = c(3,0.5))
findFreqTerms(sms_dtm_train, 5)
sms_freq<- findFreqTerms(sms_dtm_train, 5)
str(sms_freq)
sms_dtm_freq_train<-sms_dtm_train[,sms_freq]
sms_dtm_freq_test<-sms_dtm_test[,sms_freq]
convert_counts<-function(x){
  x<-ifelse(x>0,"yes","no")
}
sms_train<-apply(sms_dtm_freq_train, MARGIN = 2, convert_counts)
sms_test<-apply(sms_dtm_freq_test, MARGIN = 2, convert_counts)
#install.packages("e1071")
library("e1071")
sms_classifier<- naiveBayes(sms_train,sms_train_labels,laplace = 0)
sms_test_predict<- predict(sms_classifier,sms_test, type = "class")

install.packages("gmodels")
library("gmodels")
CrossTable(sms_test_predict , sms_test_labels , prop.chisq = FALSE, prop.t = FALSE, dnn = c('predicted' , 'actual' ))
